### Get Health info
GET http://localhost:8080/api/simulator/payment-terminal/v1/health



####################################################################################
### 
### Log-on host/device with username/password and exchange for access token
### Access token has exipry of 24 hour
### 
####################################################################################

### DEVICE
POST http://localhost:8080/api/simulator/payment-terminal/v1/auth
Content-type: application/json
Authorization: Basic terminal:terminal

{
  "merchantId": "ENZO",
  "terminalId": "123456"
}

### HOST
POST http://localhost:8080/api/simulator/payment-terminal/v1/auth
Content-type: application/json
Authorization: Basic host:host

{
  "hostId": "DEMOAPP"
}


####################################################################################
### 
### Create a new transaction
###
### Host can create a new transaction if simulator is in IDLE state
### Device has to start processing the new transaction within 5s after new transaction is created 
### 
####################################################################################

### HOST: Create a new transaction
POST http://localhost:8080/api/simulator/payment-terminal/v1/enzosystems/123456/transactions
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiaG9zdCIsInVzZXIiOiJERU1PQVBQIiwiaWF0IjoxNjkwMTkxODMwLCJleHAiOjE2OTAyNzgyMzAsImlzcyI6IkVuem9zeXN0ZW1zIn0.X51LzBuqSQ3QuNJHi8BSnt3Qp4s4Uv96bA0TeRAuANo

{
  "amountToPay": 250013,
  "locale": "nl-NL",
  "currency": "EUR",
  "reference": "abcdefg"
}

### DEVICE: Start processing new transaction
POST http://localhost:8080/api/simulator/payment-terminal/v1/enzosystems/123456/transactions
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiZGV2aWNlIiwidXNlciI6IjEyMzQ1NiIsImlhdCI6MTY5MDE5MTgwOSwiZXhwIjoxNjkwMjc4MjA5LCJpc3MiOiJFbnpvc3lzdGVtcyJ9.YEzEGM7yjeJEBlFZUp8ZIPMkWb4D9nIN0LoxWx5w7zk

{
  "action": "RUN"
}

####################################################################################
### 
### Update active transaction
###
### Device can update the state of active transaction
### 
####################################################################################


### React Terminal: Update current transaction
PUT http://localhost:8080/api/simulator/payment-terminal/v1/enzosystems/123456/transactions/fb408ee6-5240-4933-97af-d9d7d599b4ce
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiZGV2aWNlIiwidXNlciI6IjEyMzQ1NiIsImlhdCI6MTY5MDE5MTgwOSwiZXhwIjoxNjkwMjc4MjA5LCJpc3MiOiJFbnpvc3lzdGVtcyJ9.YEzEGM7yjeJEBlFZUp8ZIPMkWb4D9nIN0LoxWx5w7zk

{
  "action": "FINISH",
  "amountPaid": 250013,
  "scheme": "MASTERCARD",
  "pan": "5678542365654321"
}


####################################################################################
### 
### Stop active transaction
###
### Device/Host can stop active transaction
### 
####################################################################################

### HOST
PUT http://localhost:8080/api/simulator/payment-terminal/v1/enzosystems/123456/transactions/e0ff81d7-745f-4c4e-bf6d-a1dc50b4366c
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiaG9zdCIsInVzZXIiOiJERU1PQVBQIiwiaWF0IjoxNjkwMTkxODMwLCJleHAiOjE2OTAyNzgyMzAsImlzcyI6IkVuem9zeXN0ZW1zIn0.X51LzBuqSQ3QuNJHi8BSnt3Qp4s4Uv96bA0TeRAuANo

{
  "action": "STOP"
}

### DEVICE
PUT http://localhost:8080/api/simulator/payment-terminal/v1/enzosystems/123456/transactions/e0ff81d7-745f-4c4e-bf6d-a1dc50b4366c
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiZGV2aWNlIiwidXNlciI6IjEyMzQ1NiIsImlhdCI6MTY5MDE5MTgwOSwiZXhwIjoxNjkwMjc4MjA5LCJpc3MiOiJFbnpvc3lzdGVtcyJ9.YEzEGM7yjeJEBlFZUp8ZIPMkWb4D9nIN0LoxWx5w7zk

{
  "action": "STOP"
}

### DEVICE   - pincode verkeerd
PUT http://localhost:8080/api/simulator/payment-terminal/v1/enzosystems/123456/transactions/89fafa60-ce74-4a69-a38a-9470821abc6c
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiZGV2aWNlIiwidXNlciI6IjEyMzQ1NiIsImlhdCI6MTY5MDE5MTgwOSwiZXhwIjoxNjkwMjc4MjA5LCJpc3MiOiJFbnpvc3lzdGVtcyJ9.YEzEGM7yjeJEBlFZUp8ZIPMkWb4D9nIN0LoxWx5w7zk

{
  "action": "FAIL"
}

### DEVICE   - onvoldoende account
PUT http://localhost:8080/api/simulator/payment-terminal/v1/enzosystems/123456/transactions/9a66d94f-47f6-4272-bc25-b81734270391
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiZGV2aWNlIiwidXNlciI6IjEyMzQ1NiIsImlhdCI6MTY5MDE5MTgwOSwiZXhwIjoxNjkwMjc4MjA5LCJpc3MiOiJFbnpvc3lzdGVtcyJ9.YEzEGM7yjeJEBlFZUp8ZIPMkWb4D9nIN0LoxWx5w7zk

{
  "action": "DECLINE"
}



####################################################################################
### 
### Get transaction(s)
###
### Host can retrieve a specific transaction or all transactions
### 
####################################################################################

### HOST: Get transaction
GET http://localhost:8080/api/simulator/payment-terminal/v1/enzosystems/123456/transactions/fb408ee6-5240-4933-97af-d9d7d599b4ce
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiaG9zdCIsInVzZXIiOiJERU1PQVBQIiwiaWF0IjoxNjkwMTkxODMwLCJleHAiOjE2OTAyNzgyMzAsImlzcyI6IkVuem9zeXN0ZW1zIn0.X51LzBuqSQ3QuNJHi8BSnt3Qp4s4Uv96bA0TeRAuANo



### DEVICE: Get transaction
GET http://localhost:8080/api/simulator/payment-terminal/v1/enzosystems/123456/transactions/fb408ee6-5240-4933-97af-d9d7d599b4ce
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiZGV2aWNlIiwidXNlciI6IjEyMzQ1NiIsImlhdCI6MTY5MDE5MTgwOSwiZXhwIjoxNjkwMjc4MjA5LCJpc3MiOiJFbnpvc3lzdGVtcyJ9.YEzEGM7yjeJEBlFZUp8ZIPMkWb4D9nIN0LoxWx5w7zk




### HOST: Get all transactions
GET http://localhost:8080/api/simulator/payment-terminal/v1/enzosystems/123456/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiaG9zdCIsInVzZXIiOiJERU1PQVBQIiwiaWF0IjoxNjkwMTkxODMwLCJleHAiOjE2OTAyNzgyMzAsImlzcyI6IkVuem9zeXN0ZW1zIn0.X51LzBuqSQ3QuNJHi8BSnt3Qp4s4Uv96bA0TeRAuANo

####################################################################################
### 
### Delete transaction(s)
###
### Host can delete a specific transaction or all transactions
### 
####################################################################################

### HOST: Delete transaction
DELETE http://localhost:8080/api/simulator/payment-terminal/v1/enzosystems/123456/transactions/238cb1ad-45b3-490d-88b6-feb4adde57a7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiaG9zdCIsInVzZXIiOiJERU1PQVBQIiwiaWF0IjoxNjkwMTkxODMwLCJleHAiOjE2OTAyNzgyMzAsImlzcyI6IkVuem9zeXN0ZW1zIn0.X51LzBuqSQ3QuNJHi8BSnt3Qp4s4Uv96bA0TeRAuANo

### HOST: Delete all transactions
DELETE http://localhost:8080/api/simulator/payment-terminal/v1/enzosystems/123456/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiaG9zdCIsInVzZXIiOiJERU1PQVBQIiwiaWF0IjoxNjkwMTkxODMwLCJleHAiOjE2OTAyNzgyMzAsImlzcyI6IkVuem9zeXN0ZW1zIn0.X51LzBuqSQ3QuNJHi8BSnt3Qp4s4Uv96bA0TeRAuANo

######################################################################################
### TEST ERROR SITUATIONS
######################################################################################

### Host: Hosts are NOT ALLOWED to update current transaction, so error
PUT http://localhost:8080/api/simulator/payment-terminal/v1/enzosystems/123456/transactions/38dd60a3-75ed-4df0-a61a-1085ed3c8f51
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiaG9zdCIsInVzZXIiOiJERU1PQVBQIiwiaWF0IjoxNjkwMTkxODMwLCJleHAiOjE2OTAyNzgyMzAsImlzcyI6IkVuem9zeXN0ZW1zIn0.X51LzBuqSQ3QuNJHi8BSnt3Qp4s4Uv96bA0TeRAuANo
{
  "status": "FINISHED",
  "amountPaid": 250013,
  "scheme": "MASTERCARD",
  "pan": "5678542365654321"
}