### Get Health info
GET http://localhost:9010/api/simulator/card-dispenser/v1/health


####################################################################################
### Log-on host/device with username/password and exchange for access token (24 hours valid)
####################################################################################

@ACCESS_TOKEN_DEVICE=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiZGV2aWNlIiwidXNlciI6IkNhcmREaXNwZW5zZXIiLCJpYXQiOjE2OTU5OTMyNjIsImV4cCI6MTY5NjA3OTY2MiwiaXNzIjoiRW56b3N5c3RlbXMifQ.sy0PeU_WW-3j13NTBc8ep9tGkaYblJKUD-UR5-4prwA
@ACCESS_TOKEN_HOST=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiaG9zdCIsInVzZXIiOiJERU1PQVBQIiwiaWF0IjoxNjk2MDAwMjg5LCJleHAiOjE2OTYwODY2ODksImlzcyI6IkVuem9zeXN0ZW1zIn0.5nR6fBjdJ4wRHxx3G5lJggHWeI-ElN3Ep3cvAU9vhGM

### DEVICE
POST http://localhost:9010/api/simulator/card-dispenser/v1/auth
Content-type: application/json
Authorization: Basic device:device

{
  "deviceId": "CardDispenser"
}

### HOST
POST http://localhost:9010/api/simulator/card-dispenser/v1/auth
Content-type: application/json
Authorization: Basic host:host

{
  "hostId": "DEMOAPP"
}


####################################################################################
### Set device status and connect it to the back-end (DEVICE only, call on regular base, check .env for time-out)
####################################################################################

### DEVICE
PUT http://localhost:9010/api/simulator/card-dispenser/v1/status
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_DEVICE}}

{
  "binStatus": "EMPTY",
  "cardPosition": "STACK",
  "status": "CONNECTED",
  "stackStatus": "FULL"
}


####################################################################################
### Get device status (HOST)
####################################################################################

### HOST
GET http://localhost:9010/api/simulator/card-dispenser/v1/CardDispenser/status
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

### HOST
GET http://localhost:9010/api/simulator/card-dispenser/v1/CardDispenser/status?referenceDeviceStatus=DISCONNECTED
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}


####################################################################################
### POST request for creating new cards and requesting statuses etc (HOST)
####################################################################################

### HOST create new key
POST http://localhost:9010/api/simulator/card-dispenser/v1/session
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

{
  "deviceId": "CardDispenser",
  "command": "CREATE_CARD",
  "data": {
    "roomAccess": ["123"],
    "additionalAccess": ["SPA"],
    "startDateTime": "2023-12-31T15:00Z",
    "endDateTime": "2023-08-16T11:00:00"
  }
}

### HOST retract card
POST http://localhost:9010/api/simulator/card-dispenser/v1/session
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

{
  "command": "RETRACT_CARD_NOT_TAKEN",
  "deviceId": "CardDispenser"
}

### HOST send faulty card to bin
POST http://localhost:9010/api/simulator/card-dispenser/v1/session
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

{
  "command": "SEND_FAULTY_CARD_TO_BIN",
  "deviceId": "CardDispenser"
}

### HOST request to cancel session by id
PATCH http://localhost:9010/api/simulator/card-dispenser/v1/session/4977bffa-c6a5-47fc-a8e4-e52a7c6a1c8d
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

{
  "command": "CANCEL"
}

### HOST request to cancel session by id
PUT http://localhost:9010/api/simulator/card-dispenser/v1/session/4977bffa-c6a5-47fc-a8e4-e52a7c6a1c8d
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

{
  "command": "CANCEL"
}

### HOST get session by id
GET http://localhost:9010/api/simulator/card-dispenser/v1/session/e92e0dd2-cb85-49ca-9c88-8dac2c7ad01b
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}


####################################################################################
### Receive new card data from backend to write to new card (DEVICE only)
####################################################################################

### DEVICE get active session, uses long polling if there is no active session at time of calling this endpoint
GET http://localhost:9010/api/simulator/card-dispenser/v1/active-session
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_DEVICE}}

### DEVICE finish creation of new card
PUT http://localhost:9010/api/simulator/card-dispenser/v1/active-session
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_DEVICE}}

{
  "data": {
    "status": "FINISHED"
  }
}

### DEVICE retract card not taken / send faulty card to bin
PUT http://localhost:9010/api/simulator/card-dispenser/v1/active-session
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN_DEVICE}}

{
  "data": {
    "status": "FINISHED"
  }
}

### DEVICE stop session when host asked for a cancellation
PUT http://localhost:9010/api/simulator/card-dispenser/v1/active-session
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_DEVICE}}

{
  "data": {
    "status": "STOPPED"
  }
}
