### Get Health info
GET http://localhost:9010/api/simulator/card-dispenser/v1/health


####################################################################################
### Log-on host/device with username/password and exchange for access token (24 hours valid)
####################################################################################

@ACCESS_TOKEN_DEVICE=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiZGV2aWNlIiwidXNlciI6IkNhcmREaXNwZW5zZXIiLCJpYXQiOjE2OTY5NDc0NzQsImV4cCI6MTY5NzAzMzg3NCwiaXNzIjoiRW56b3N5c3RlbXMifQ.cgch58o7DK5H7pwuyiF-s_DlPSVMZkB_4SWkWYeyHmI
@ACCESS_TOKEN_HOST=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiaG9zdCIsInVzZXIiOiJERU1PQVBQIiwiaWF0IjoxNjk2OTIyMjk2LCJleHAiOjE2OTcwMDg2OTYsImlzcyI6IkVuem9zeXN0ZW1zIn0.tpuh7x31yv7FLfXK2kp1kYiY7TWrSKyazRN1OoQqQyc
@DEVICE_ID=CardDispenser
@SESSION_ID=17f3f180-3570-467d-909e-36ffcf36d492


####################################################################################
### POST request for creating new cards and requesting statuses etc (HOST)
####################################################################################

### HOST get session by id
GET http://localhost:9010/api/simulator/card-dispenser/v1/session/{{SESSION_ID}}
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

### HOST create new key
POST http://localhost:9010/api/simulator/card-dispenser/v1/session
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

{
  "deviceId": "{{DEVICE_ID}}",
  "command": "CREATE_CARD",
  "data": {
    "roomAccess": ["123"],
    "additionalAccess": ["SPA"],
    "startDateTime": "2023-12-31T15:00Z",
    "endDateTime": "2023-08-16T11:00:00"
  }
}

### HOST request to read card by id
PUT http://localhost:9010/api/simulator/card-dispenser/v1/session/{{SESSION_ID}}
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

{
  "command": "READ_CARD",
  "deviceId": "{{DEVICE_ID}}"
}

### HOST present card by id
PUT http://localhost:9010/api/simulator/card-dispenser/v1/session/{{SESSION_ID}}
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

{
  "command": "PRESENT_CARD",
  "deviceId": "{{DEVICE_ID}}"
}

### HOST retract card by id
PUT http://localhost:9010/api/simulator/card-dispenser/v1/session/{{SESSION_ID}}
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

{
  "command": "RETRACT_CARD_NOT_TAKEN",
  "deviceId": "{{DEVICE_ID}}"
}

### HOST send faulty card to bin by id
PUT http://localhost:9010/api/simulator/card-dispenser/v1/session/{{SESSION_ID}}
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

{
  "command": "SEND_FAULTY_CARD_TO_BIN",
  "deviceId": "{{DEVICE_ID}}"
}

### HOST request to cancel session by id
PUT http://localhost:9010/api/simulator/card-dispenser/v1/session/{{SESSION_ID}}
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

{
  "command": "CANCEL"
}

####################################################################################
### Get Tokens
####################################################################################


### DEVICE
POST http://localhost:9010/api/simulator/card-dispenser/v1/auth
Content-type: application/json
Authorization: Basic device:device

{
  "deviceId": "{{DEVICE_ID}}"
}

### HOST
POST http://localhost:9010/api/simulator/card-dispenser/v1/auth
Content-type: application/json
Authorization: Basic host:host

{
  "hostId": "DEMOAPP"
}


####################################################################################
### Set device status and connect it to the back-end (DEVICE only, call on regular base, check .env for time-out)
####################################################################################

### DEVICE
PUT http://localhost:9010/api/simulator/card-dispenser/v1/status
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_DEVICE}}

{
  "binStatus": "EMPTY",
  "cardPosition": "STACK",
  "status": "CONNECTED",
  "stackStatus": "FULL"
}


####################################################################################
### Get device status (HOST)
####################################################################################

### HOST
GET http://localhost:9010/api/simulator/card-dispenser/v1/{{DEVICE_ID}}/status
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

### HOST
GET http://localhost:9010/api/simulator/card-dispenser/v1/{{DEVICE_ID}}/status?referenceDeviceStatus=DISCONNECTED
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}


####################################################################################
### Receive new card data from backend to write to new card (DEVICE only)
####################################################################################

### DEVICE get active session, uses long polling if there is no active session at time of calling this endpoint
GET http://localhost:9010/api/simulator/card-dispenser/v1/active-session
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_DEVICE}}

### DEVICE finish creation of new card (host auto sets status = CREATED)
PUT http://localhost:9010/api/simulator/card-dispenser/v1/active-session
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_DEVICE}}

{
  "data": {
    "status": "CREATED"
  }
}

### DEVICE read card (host auto sets status = READ)
PUT http://localhost:9010/api/simulator/card-dispenser/v1/active-session
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN_DEVICE}}

{
  "data": {
    "cardId": "0",
    "roomAccess": [
      "100"
    ],
    "additionalAccess": [
      "POOL"
    ],
    "startDateTime": "2023-10-10",
    "endDateTime": "2023-10-11"
  }
}

### DEVICE presented card taken (not sure if data necessary)
PUT http://localhost:9010/api/simulator/card-dispenser/v1/active-session
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN_DEVICE}}

{
  "data": {
    "status": "FINISHED"
  }
}

### DEVICE retract card not taken / send faulty card to bin
PUT http://localhost:9010/api/simulator/card-dispenser/v1/active-session
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN_DEVICE}}

{
  "data": {
    "status": "FINISHED"
  }
}

### DEVICE stop session when host asked for a cancellation
PUT http://localhost:9010/api/simulator/card-dispenser/v1/active-session/
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_DEVICE}}

{
  "data": {
    "status": "STOPPED"
  }
}
