enum SESSION_STATUS {
  ACTIVE = 'ACTIVE',
  CANCELLING = 'CANCELLING',
  CREATED = 'CREATED',
  SCANNED = 'SCANNED',
  FINISHED = 'FINISHED',
  STOPPED = 'STOPPED',
  TIMED_OUT = 'TIMED_OUT'
};

export default SESSION_STATUS;