enum SESSION_COMMAND {
  CANCEL = 'CANCEL',
  CREATE_CARD = 'CREATE_CARD',
  RETRACT_CARD_NOT_TAKEN = 'RETRACT_CARD_NOT_TAKEN',
  SEND_FAULTY_CARD_TO_BIN = 'SEND_FAULTY_CARD_TO_BIN'
};

export default SESSION_COMMAND;