const DEVICE_STATUS = {
  CONNECTED: 'CONNECTED',
  DISCONNECTED: 'DISCONNECTED',
  OUT_OF_ORDER: 'OUT_OF_ORDER',
  NOT_FOUND: 'NOT_FOUND'
};

const SESSION_COMMAND = {
  SCAN_BARCODE: 'SCAN_BARCODE',
  STOP_SCANNING: 'STOP_SCANNING'
};

const SESSION_STATUS = {
  WAITING_FOR_BARCODE: 'WAITING_FOR_BARCODE',
  FINISHED: 'FINISHED',
  STOPPED: 'STOPPED',
  TIMED_OUT: 'TIMED_OUT'
};

const LONG_POLLING_INTERVAL_MS = 250;

module.exports = {
  DEVICE_STATUS,
  SESSION_COMMAND,
  SESSION_STATUS,
  LONG_POLLING_INTERVAL_MS
};
