### Get Health info
GET http://localhost:9007/api/simulator/id-scanner/v1/health


####################################################################################
### Log-on host/device with username/password and exchange for access token (24 hours valid)
####################################################################################

@ACCESS_TOKEN_DEVICE=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiZGV2aWNlIiwidXNlciI6IktleUVuY29kZXJ0ZXN0IiwiaWF0IjoxNjk1Mjk1Nzk2LCJleHAiOjE2OTUzODIxOTYsImlzcyI6IkVuem9zeXN0ZW1zIn0.oF5o9IShy4N-r0Kdol2q5Xj6o6cIASDWd9-JIHifwC0
@ACCESS_TOKEN_HOST=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiaG9zdCIsInVzZXIiOiJERU1PQVBQIiwiaWF0IjoxNjk1NjM0MjM5LCJleHAiOjE2OTU3MjA2MzksImlzcyI6IkVuem9zeXN0ZW1zIn0.E95p76DqyBobsBgz9uBJq4vc3dHEUasoGOiGVzGHe1w



### DEVICE
POST http://localhost:9007/api/simulator/id-scanner/v1/auth
Content-type: application/json
Authorization: Basic device:device

{
  "deviceId": "IdScanner"
}

### HOST
POST http://localhost:9007/api/simulator/id-scanner/v1/auth
Content-type: application/json
Authorization: Basic host:host

{
  "hostId": "DEMOAPP"
}

####################################################################################
### Set device status and connect it to the back-end (DEVICE only, call on regular base, check .env for time-out)
####################################################################################

### DEVICE
PUT http://localhost:9007/api/simulator/id-scanner/v1/status
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_DEVICE}}

{
  "status": "CONNECTED"
}

####################################################################################
### Get device status (HOST)
####################################################################################

### HOST
GET http://localhost:9007/api/simulator/id-scanner/v1/IdScanner/status
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

### HOST
GET http://localhost:9007/api/simulator/id-scanner/v1/IdScanner/status?referenceDeviceStatus=DISCONNECTED
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

####################################################################################
### POST requests for scanning IDs (HOST)
####################################################################################
### HOST read ID
POST http://localhost:9007/api/simulator/id-scanner/v1/session
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

{
  "deviceId": "IdScanner",
  "command": "SCAN_ID"
}

### HOST request to cancel session by id
PATCH http://localhost:9007/api/simulator/id-scanner/v1/session/4d99db59-c0a6-404c-af03-87ca834369a6
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

{
  "command": "CANCEL"
}

### HOST request to cancel session by id
PUT http://localhost:9007/api/simulator/id-scanner/v1/session/d4cea207-2143-4558-975a-9e2fa01ba2f5
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

{
  "command": "CANCEL"
}

### HOST get session by id
GET http://localhost:9007/api/simulator/id-scanner/v1/session/e04c4532-d034-44c4-8088-86d008d59442
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}



####################################################################################
### Send existing key data from scanned key to backend, receive new key date from backend to write to new key (DEVICE only)
####################################################################################

### DEVICE get active session, uses long polling if there is no active session at time of calling this endpoint
GET http://localhost:9007/api/simulator/id-scanner/v1/active-session
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_DEVICE}}

### DEVICE finish reading an existing key
PUT http://localhost:9007/api/simulator/id-scanner/v1/active-session
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_DEVICE}}

{
  "data": {
    "status": "FINISHED",
    "dateOfBirth": "661231",
    "dateOfExpiry": "661231",
    "documentNumber": "IdScanner789",
    "documentType": "P<",
    "issuerCode": "NLD",
    "namePrimary": "Erik",
    "nameSecondary": "de Vries",
    "nationality": "NLD",
    "sex": "M",
    "images": {
      "cardHolder": "imagehere",
      "docFront": "imagehere",
      "docBack": "imagehere"
    }
  }
}

### DEVICE stop session when host asked for a cancellation
PUT http://localhost:9007/api/simulator/id-scanner/v1/active-session
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_DEVICE}}

{
  "data": {
    "status": "STOPPED"
  }
}

