enum ActionType {
  CLICKED_BACK,
  CLICKED_CROSS,
  SHOW_BIN_SETTINGS,
  SHOW_BACK,
  SHOW_CROSS,
  SHOW_STACK_SETTINGS,
  RECEIVE_KEY_DATA,
  SET_HEADER_TITLE,
  TOGGLE_SETTINGS,
}

export default ActionType;
