enum AppActions {
  CLICKED_BACK,
  CLICKED_CROSS,
  SHOW_BIN_SETTINGS,
  SHOW_BACK,
  SHOW_CROSS,
  SHOW_STACK_SETTINGS,
  RECEIVE_CARD_DATA,
  SET_CARDSTACK,
  SET_BINSTACK,
  SET_HEADER_TITLE,
  TOGGLE_SETTINGS,
}

export default AppActions;
