enum OPSTATE {
  DEVICE_START_UP = 'DEVICE_START_UP',
  DEVICE_CONNECT = 'DEVICE_CONNECT',
  DEVICE_DISCONNECT = 'DEVICE_DISCONNECT',
  DEVICE_IDLE = 'DEVICE_IDLE',
  DEVICE_CREATING_A_KEY = 'DEVICE_CREATING_A_KEY',
  WAITING_FOR_READ_COMMAND = 'WAITING_FOR_READ_COMMAND',
  DEVICE_READING_A_KEY = 'DEVICE_READING_A_KEY',
  WAITING_FOR_FINAL_COMMAND = 'WAITING_FOR_FINAL_COMMAND',
  // that can be RETRACT_CARD_NOT_TAKEN, SEND_FAULTY_CARD_TO_BIN and PRESENTCARD
  DEVICE_PRESENT_CARD = 'DEVICE_PRESENT_CARD',
  DEVICE_PUT_IN_STACK = 'DEVICE_PUT_IN_STACK',
  DEVICE_PUT_IN_BIN = 'DEVICE_PUT_IN_BIN',
  //
  DEVICE_DISCONNECTED = 'DEVICE_DISCONNECTED',
  DEVICE_COULD_NOT_CONNECT = 'DEVICE_COULD_NOT_CONNECT',
  DEVICE_COULD_NOT_DISCONNECT = 'DEVICE_COULD_NOT_DISCONNECT',
  DEVICE_OUT_OF_ORDER = 'DEVICE_OUT_OF_ORDER',

  API_CANCEL = 'API_CANCEL',
  TAKING_THE_KEY = 'TAKING_THE_KEY',
  KEY_SUCCESFULLY_CANCELLED = 'KEY_SUCCESFULLY_CANCELLED',
  KEY_SUCCESSFULLY_PUT_TO_STACK = 'KEY_SUCCESSFULLY_PUT_TO_STACK',
  KEY_SUCCESSFULLY_TAKEN = 'KEY_SUCCESSFULLY_TAKEN',
  KEY_SUCCESSFULLY_REJECTED = 'KEY_SUCCESSFULLY_REJECTED',
  SERVER_ERROR = 'SERVER_ERROR',
}
export default OPSTATE;
