enum OPSTATE {
  DEVICE_START_UP,
  DEVICE_CONNECT,
  DEVICE_DISCONNECT,
  DEVICE_IDLE,
  DEVICE_DISCONNECTED,
  DEVICE_COULD_NOT_CONNECT,
  DEVICE_COULD_NOT_DISCONNECT,
  DEVICE_OUT_OF_ORDER,
  DEVICE_CREATING_A_KEY,
  DEVICE_KEY_IS_READY,
  API_CANCEL,
  API_TIMED_OUT,
  DEVICE_IS_SCANNING,
  API_SCAN_FAILED,
  API_SCAN_SUCCESS,
  SERVER_ERROR,
}
export default OPSTATE;
