enum SESSIONSTATUS {
  ACTIVE = 'ACTIVE',
  CREATED = 'CREATED',
  CANCELLING = 'CANCELLING',
  FINISHED = 'FINISHED',
  STOPPED = 'STOPPED',
  TIMED_OUT = 'TIMED_OUT',
}
export default SESSIONSTATUS;
