import { APPSETTINGS, DEVICESTATUSOPTIONS, STACKSTATUSES, BINSTATUSES, CARDPOSITIONS, FAILPROCESS, BINPOLICY } from '../enums/SettingEnums';

export type SettingStateType = {
  [APPSETTINGS.DEVICE_STATUS]: DEVICESTATUSOPTIONS,
  [APPSETTINGS.CARD_STACK]: STACKSTATUSES,
  [APPSETTINGS.BIN]: BINSTATUSES,
  [APPSETTINGS.CARD_POSITION]: CARDPOSITIONS,
  [APPSETTINGS.FAIL_PROCESS]: FAILPROCESS,
  [APPSETTINGS.BIN_POLICY]: BINPOLICY,
  statusSettingIsClicked: boolean;
  cardStackSettingIsClicked: boolean;
  binStackSettingIsClicked: boolean;
};
