import { APPSETTINGS, DEVICESTATUSOPTIONS, STACKSTATUSES, BINSTATUSES, CARDPOSITIONS, FAILPROCESS } from '../enums/SettingEnums';

export type SettingStateType = {
  [APPSETTINGS.DEVICE_STATUS]: DEVICESTATUSOPTIONS,
  [APPSETTINGS.CARD_STACK]: STACKSTATUSES,
  [APPSETTINGS.BIN]: BINSTATUSES,
  [APPSETTINGS.CARD_POSITION]: CARDPOSITIONS,
  [APPSETTINGS.FAIL_PROCESS]: FAILPROCESS,
  statusSettingIsClicked: boolean;
};
