### Get Health info
GET http://localhost:9001/api/simulator/barcode-scanner/v1/health


@ACCESS_TOKEN_DEVICE=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiZGV2aWNlIiwidXNlciI6IkJhcmNvZGVTY2FubmVyIiwiaWF0IjoxNjkyNzQ0MzEwLCJleHAiOjE2OTI4MzA3MTAsImlzcyI6IkVuem9zeXN0ZW1zIn0.ZSOHS1LE0XeBKImd4tf0QtTPH6sxfYQkODLn_YvrWTs
@ACCESS_TOKEN_HOST=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiaG9zdCIsInVzZXIiOiJERU1PQVBQIiwiaWF0IjoxNjkyNzc1NDUwLCJleHAiOjE2OTI4NjE4NTAsImlzcyI6IkVuem9zeXN0ZW1zIn0.2z6mfIhghgxOe56Jr5zgCkYuSl98YzAeSkYCpu2OL5w

####################################################################################
### Log-on host/device with username/password and exchange for access token (24 hours valid)
####################################################################################

### DEVICE
POST http://localhost:9001/api/simulator/barcode-scanner/v1/auth
Content-type: application/json
Authorization: Basic device:device

{
  "deviceId": "BarcodeScanner"
}

### HOST
POST http://localhost:9001/api/simulator/barcode-scanner/v1/auth
Content-type: application/json
Authorization: Basic host:host

{
  "hostId": "DEMOAPP"
}


####################################################################################
### Set device status and connect it to the back-end (DEVICE only, call on regular base, check .env for setting the time-out)
####################################################################################

### DEVICE
PUT http://localhost:9001/api/simulator/barcode-scanner/v1/status
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_DEVICE}}

{
  "status": "CONNECTED"
}

####################################################################################
### Get device status (HOST)
####################################################################################

### HOST
GET http://localhost:9001/api/simulator/barcode-scanner/v1/status
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}


### HOST
GET http://localhost:9001/api/simulator/barcode-scanner/v1/status?referenceStatus=NOT_FOUND&longPollingMS=3500
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

####################################################################################
### Start scanning by creating a new session (HOST)
####################################################################################

### HOST 
POST http://localhost:9001/api/simulator/barcode-scanner/v1/session
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

{
  "command": "SCAN_BARCODE",
  "timeoutMS": 30000
}

####################################################################################
### Stop scanning by stopping a running session (HOST)
####################################################################################

### HOST 
PUT http://localhost:9001/api/simulator/barcode-scanner/v1/session/244fa2a7-b8c7-41fe-8259-b25dcb12866e
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}

{
  "command": "STOP_SCANNING"
}

####################################################################################
### Get a scan session by sessionId, optionally with long polling (HOST)
####################################################################################

### HOST 
GET http://localhost:9001/api/simulator/barcode-scanner/v1/session/244fa2a7-b8c7-41fe-8259-b25dcb12866e
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}


### HOST 
GET http://localhost:9001/api/simulator/barcode-scanner/v1/session/8c772f05-3e9b-439b-9ff1-82dcacd7ab33?longPollingMS=20000&currentStatus=WAITING_FOR_BARCODE
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_HOST}}






####################################################################################
### Get active session (DEVICE)
####################################################################################

### DEVICE 
GET http://localhost:9001/api/simulator/barcode-scanner/v1/active-session
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_DEVICE}}

####################################################################################
### Update active session with scanned barcodeData (DEVICE)
####################################################################################

### DEVICE
PUT http://localhost:9001/api/simulator/barcode-scanner/v1/active-session
Content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN_DEVICE}}

{
  "barcodeData": "Whatever data stored in the QR-code"
}
