### Run endpoint
GET http://localhost:8000/payment_terminal

### Start payment
POST http://localhost:8000/payment_terminal/123/payment
Content-Type: application/json

{
   "amount":100
}


### Get status
GET http://localhost:8000/payment_terminal/123/payment/2fa8e64fd9f95fc9