### Run endpoint
GET http://localhost:8080/payment_terminal

### Start payment
POST http://localhost:8080/payment_terminal/123/payment
Content-Type: application/json

{
   "amount": 200
}

### Get status
GET http://localhost:8080/payment_terminal/123/payment/251a5fba48be7c3d
