const DEVICE_STATUS = {
  CONNECTED: 'CONNECTED',
  DISCONNECTED: 'DISCONNECTED',
  OUT_OF_ORDER: 'OUT_OF_ORDER',
  NOT_FOUND: 'NOT_FOUND'
};

const SESSION_COMMAND = {
  CREATE_KEY: 'CREATE_KEY',
  READ_KEY: 'READ_KEY',
  STOP: 'STOP'
};

const SESSION_STATUS = {
  WAITING_FOR_KEY: 'WAITING_FOR_KEY',
  FINISHED: 'FINISHED',
  STOPPED: 'STOPPED',
  TIMED_OUT: 'TIMED_OUT'
};

const CREATION_MODE = {
  NEW: 'NEW',
  COPY: 'COPY',
  JOINING: 'JOINING'
};

const LONG_POLLING_INTERVAL_MS = 250;

module.exports = {
  DEVICE_STATUS,
  SESSION_COMMAND,
  SESSION_STATUS,
  CREATION_MODE,
  LONG_POLLING_INTERVAL_MS
};
