enum AddKeyFieldsEnum {
  ADDITIONAL_ACCESS = 'ADDITIONAL_ACCESS',
  END_DATE_TIME = 'END_DATE_TIME',
  ID = 'ID',
  ROOM_ACCESS = 'ROOM_ACCESS',
  START_DATE_TIME = 'START_DATE_TIME',
}

export default AddKeyFieldsEnum;
